### ISSUE TITLE
[Bug] container won't start

### ISSUE THREAD

**Issue by jpriebe** [philosowaffle/ambientweather-local-server#41]
Container won't start - watching the events, I can see the container dies right away, and the only thing it has in the logs is this:

```
chown: changing ownership of '/app/configuration.local.json': Read-only file system
```

My `docker-compose` is essentially the same as the example in the documentation.

```
  ambient-weather:
    container_name: ambient-weather-server
    image: philosowaffle/ambientweather-local-server:latest
    ports:
      - 8001:8080
    environment:
      - TZ=America/Chicago
    volumes:
      - /appdata/ambient-weather/configuration.local.json:/app/configuration.local.json:ro
      - /appdata/ambient-weather/output:/app/output # optional, logs may be written here based on your configuration
```

I don't understand why the code is calling `chown` on `/app` when the volume mapping specifically puts a read-only file into the `/app` directory.

But I'm pretty sure that `chown` is failing, causing the entrypoint script to bail out and the container won't start.

Using Fedora Server 40.
